### ISSUE TITLE
ServiceMonitor.monitoring.coreos.com "prometheus-exporter" is invalid: spec.endpoints: Required value

### ISSUE THREAD

**Issue by dabo-devconsole** [kubescape/helm-charts#390] opened 2024-02-07 20:25 UTC
# Description
Helm installation fails to deploy the prometheus-exporter ServiceMonitor.

# Environment
OS: Ubuntu 22.04 LTS 
Version: 3.0.3
 
# Steps To Reproduce
1.  --set "capabilities.prometheusExporter=enable" or set value in values.yaml
2. helm install ...
3. install all, but prometheus-exporter
4. error: Error: INSTALL FAILED: failed to create resource: ServiceMonitor.monitoring.coreos.com "prometheus-exporter" is invalid: spec.endpoints: Required value 

# Expected behavior
ServiceMonitor is created

# Actual Behavior
ServiceMonitor is not created
 

# Additional context
The template is missing the required "endpoints" specification.

**Comment by dwertent** [comment] 2024-02-19 11:54
Do you have the Prometheus operator running in your cluster?

**Comment by dabo-devconsole** [comment] 2024-02-19 13:27
Yes, the kube-prometheus-stack-operator is running in version v0.71.2 in the cluster.

**Comment by dwertent** [comment] 2024-02-19 19:37
This is unusual, I'm unable to reproduce the problem. It seems to be working fine without any issues. 
Perhaps we should consider adding the endpoint [here](https://github.com/kubescape/helm-charts/blob/main/charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml#L10) just to be cautious.

**Comment by aminrj** [comment] 2024-02-27 08:20
Hi,
I am experiencing the same issue but while using Prometheus community Helm chart:
`│ Error: failed to create resource: ServiceMonitor.monitoring.coreos.com "prometheus-exporter" is invalid: spec.endpoints: Required value`

The result is that the pod is in a CrashLoopBackOff:
`prometheus-exporter-f4dc7988f-dmf2d   0/1     CrashLoopBackOff   4 (25s ago)   117s`

**Comment by dabo-devconsole** [comment] 2024-02-29 07:42
Yes it pretty much looks the same. I'm also using the Prometheus community helm chart, especially the prometheus-community/kube-prometheus-stack.

**Comment by hyo-shin** [comment] 2024-05-16 10:50
I have also encountered this issue:

Error: failed to create resource: ServiceMonitor.monitoring.coreos.com "prometheus-exporter" is invalid: spec.endpoints: Required value

I agree with @dwertent suggestion that the spec.endpoints might need to be added [here](https://github.com/kubescape/helm-charts/blob/main/charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml#L10).

**Comment by lubgi** [comment] 2024-05-20 21:41
What's the workaround?

**Comment by dwertent** [comment] 2024-05-21 05:42
I will look into this today :)

**Comment by l-spork-cc** [comment] 2024-06-12 13:59
We are experiencing the same problem, we deployed a separate servicemonitor outside of the helm deploymeent as a workaround. The following ressource definition works for us, depending on how the prometheus instance is configured one might also need to add a label for the prometheus selector ( we disabled it completely).

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-exporter
  name: kubescape
  namespace: kubescape
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080
      path: /metrics
  namespaceSelector:
    matchNames:
      - kubescape
  selector:
    matchLabels:
      app: prometheus-exporter
```

**Comment by matthyx** [comment] 2024-09-03 13:37
@dabo-devconsole can you check with the latest chart please?

**Comment by dabo-devconsole** [comment] 2024-09-06 08:06
Hi @matthyx,
same error in Chart version 1.21.2. Do I missed something?

**Comment by matthyx** [comment] 2024-09-06 08:17
should be fixed in the next release (probably next week)

**Closed** 2024-09-06 08:17 UTC
Labels: bug
